### PR TITLE
Added Contributing Guidelines

### LINKED ISSUE #2: Add ContributingGuidelines.md
The Contributing Guideline documentation will contain set of guidelines that will help contributors during the contribution process.
File type markdown.

### PR DESCRIPTION
**Pull request by shanvijha30**
@ShwetKhatri2001 I have added the Contributing Guidelines as CONTRIBUTING.md.
Please review it.

Fixes #2

### CODE REVIEW

**Review by ShwetKhatri2001 — CHANGES_REQUESTED** [review]
Its good ! But I have some suggestions to make it better !

For the convenience of the developer, provide specific commands for setting up this project.

For that replace `<repo-name>` by `AR-Webstore`
and `<upstream-owner>` by `ShwetKhatri2001`

**Comment by ShwetKhatri2001** [comment]
Are you working on this @shanvijha30 ? If yes, then please try to complete this within the next two days.

**Comment by shanvijha30** [comment]
@ShwetKhatri2001 yes I am working on it and will complete it within the next two days.

**Comment by shanvijha30** [comment]
@ShwetKhatri2001 I have made the necessary changes.
Please review it.

**Comment by ShwetKhatri2001** [comment]
Congrats on your first PR getting merged on AR-Webstore @shanvijha30  🚀

**Pull request merged**
