### PR TITLE
WishList implemented successfully!

### PR DESCRIPTION
**Pull request by ayann07**
## Fixes Issue 
Issue No. : #195 is now fixed.

## Changes proposed
WishList section is implemented now so that user can click on the + button and item will be added to wishlist and if user want to remove the item he can again click on button to remove it. User can also remove wishlist items by going in wishlist section.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

Demo Video:-

https://github.com/ShwetKhatri2001/AR-Webstore/assets/126085856/81959d7a-cd2c-4383-b7c0-68c66dfbb4cf

I have worked this under SWOC 2024

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
I looked at your changes, and it was good. But you need to fix the failing deploy preview. Go through `
🔍 Latest deploy log` link given above.

**Comment by ayann07** [comment]
Now you may check deploy preview, it is working fine now.

**Comment by ayann07** [comment]
@ShwetKhatri2001 please see to it.

**Comment by ShwetKhatri2001** [comment]
It's breaking many of the existing features and having issues like in the home page all items are in a single column, the feedback page is small in width, sign-in and sign-up pages show 404.

The wishlist is working but I can't merge that while breaking others. Please take a look and fix those. 
You haven't merged all the latest changes yet I think.

**Comment by ayann07** [comment]
Let me fork again so I will get all data latest and then make changes then

**Comment by ayann07** [comment]
Give me 2 hours, I will create a fresh pr

**Pull request closed without merging**
