### PR TITLE
Form validation in Feedback.js

### LINKED ISSUE #230: Feedback : Form validation
### Description

while taking feedback it supports invalid name ;
in place of charecters it takes numbers

### Screenshots

Screenshot 2024-01-19 021727

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### PR DESCRIPTION
**Pull request by student-aditipaliwal**
Fixes #230

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Good work @student-aditipaliwal !
Can you make these changes to make it valid for `Easy ' level?

- `Name`, `Email`, and the first question `What did you like most about AR-Webstore?` needs to be mandatory to submit the form. Alert if they are not valid/empty.
- Similarly add validation to check valid email format and non-empty answer to the first question.
- Show error messages in light red color and small font size.

I can merge this after that.

**Comment by student-aditipaliwal** [comment]
ok I did that and submit it to you tomorrow

**Comment by ShwetKhatri2001** [comment]
Will you be able to complete this in the next few days @student-aditipaliwal ?

**Comment by ShwetKhatri2001** [comment]
Closing this PR because of inactivity.

**Pull request closed without merging**
