### PR TITLE
Centered the product list

### PR DESCRIPTION
**Pull request by Preeti8021**
## Fixes Issue 
#175 

## Changes proposed
[X] Centered the items in the product list
[X] full screen button on hover text was fixed 

image

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
On mobile screen its not in the center,

**Comment by Preeti8021** [comment]
Kindly review the changes and let me know 
image

**Comment by ShwetKhatri2001** [comment]
I noticed there is one more misplacement caused in this this PR,
If you open this preview in mobile ( or open mobile mode in desktop's developer tools ) then there are two buttons `full  screen` and `help` having icons present in the right-bottom corner and actually coming on top of `View in your space` button, that's why we kept those two buttons in the top-left corner earlier, just fix it back to the previous version ( in the top-left corner ).




Otherwise, everything is good to go. I can merge this.

**Comment by Preeti8021** [comment]
I have fixed the pr, kindly review @ShwetKhatri2001 
image

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊 Congrats on your first PR getting merged on AR-Webstore @Preeti8021 🚀 Keep Contributing 👍

**BONUS  🎁**
You're getting **3 Bonus** points for putting extra efforts in fixing responsiveness of the website.

**Pull request merged**
