### PR TITLE
Logo updated

### PR DESCRIPTION
**Pull request by Souvik34**
## Fixes Issue

Issue #190 

## Changes proposed
Logo updated

Updated the logo in the website

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [X] My change requires changes to the documentation.
- [X] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
I'd suggest few changes,
Swap the black and white colors in the logo.
Place AR-Webstore text on the right of the icon (AR) with big font-size.
Also, change the favicon with the icon (AR) present in the logo image.

Pull the latest changes of the repo, make the suggested changes and then it can be merged.

**Comment by ShwetKhatri2001** [comment]
This PR can be merged now. But your branch needs to be updated with latest code for that.

**Comment by Souvik34** [comment]
So what to do now?
🙂

**Comment by ShwetKhatri2001** [comment]
Will you be able to fix this in next few days @Souvik34 ? Let me know if you need some help.

**Comment by Souvik34** [comment]
Yes, I will merge

**Comment by Souvik34** [comment]
Actually what is the problem, I unable to find?? Please assist what to do

**Comment by ShwetKhatri2001** [comment]
If you don't wanna spend much time solving conflicts then better you create a new branch from the master branch, add your changes there, and create a new PR.

**Comment by Souvik34** [comment]
Can you close this PR ad I shall be raising another issue from SWOC of this same logo updating. Can you assign me there and I shall fix the conflicts and merge it there

**Pull request closed without merging**
