### PR TITLE
Applied Margin in about page to align heading and para in same vertical lines

### PR DESCRIPTION
**Pull request by SadafKausar2025**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by SadafKausar2025** [comment]
priviously it was not alligned proverly . tnis is privious screenshot
Screenshot (1679)

After Aligning the website looks like
Screenshot (1678)

**Comment by SadafKausar2025** [comment]
can you please assign this issue to me?

**Review by ShwetKhatri — APPROVED** [review]

**Comment by ShwetKhatri2001** [comment]
Thanks for your contribution @SadafKausar2025 ! 
LGTM 🎊 Congrats on your first PR getting merged on AR-Webstore 🚀 Keep Contributing 👍

**Comment by SadafKausar2025** [comment]
hello @ShwetKhatri 
you have merged the PR but not assign and not given level
please give level and assign to me , so that points will be added in my contribution

**Comment by ShwetKhatri2001** [comment]
The project isn't part of any open-source program. It has been part of a few in the past.

**Pull request merged**
