### PR TITLE
fix: improper buttons sizings on model viewer 🛠

### LINKED ISSUE #126: [BUG]: improper sizing of buttons on model viewer component 🪲
### Description

- This bug is about the improper sizing of buttons on model viewer component.
- Those buttons are not in the right aspect ratio, they seems to be disorted and forced to be shrinked.
- We need to fix this behaviour of buttons to improve the UI of AR-Webstore Website.

### Screenshots

|||
|:---:|:----:|
|**BEFORE**| Screenshot 2023-07-23 at 16-37-40 AR-Webstore|
|**AFTER**|Screenshot 2023-07-23 at 16-36-04 AR-Webstore |

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Firefox

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Changes proposed
- Fixed the improper measurements and eneven styling across different browsers like Chrome, Firefox, Safari Etc.
- The changes have been made by revamping the styles of both button elements.
- As per @ShwetKhatri2001 PA's request the button will be look consistent for all browsers, rest assured.

## Check List

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Hey there @ShwetKhatri2001 👋🏻 

Please make sure to review this PR.

Thank you!

**Review by ShwetKhatri2001 — CHANGES_REQUESTED** [review]
Sizing is better than before now but on mobile the placement of buttons is disturbed.
It will be good if you can place both the buttons in a next row below `View in your space` button in the right corner.

**Comment by 0xabdulkhalid** [comment]
No @ShwetKhatri2001, It's perfectly fine take a look at this picture

**Comment by ShwetKhatri2001** [comment]
> No @ShwetKhatri2001, It's perfectly fine take a look at this picture
> 
> 

Take a minute and please read that message completely. Its on mobile as shown in the screenshot.

**Comment by 0xabdulkhalid** [comment]
@ShwetKhatri2001, I can't get your point of view.

You said that the button is disturbed, but for mobile view it looks fine.

Did i want to make any other change on alignment of buttons for mobile ?
(Sorry, i can't understand the above thoughts of yours.)

**Comment by ShwetKhatri2001** [comment]
> Sizing is better than before now but on mobile the placement of buttons is disturbed. It will be good if you can place both the buttons in a next row below `View in your space` button in the right corner.
> 
> 

The two buttons (in the top-left corner ) are on top of each other as shown in the screenshot. 
The screenshot is taken for this PR's [deploy preview](https://deploy-preview-127--ar-webstore.netlify.app/).

While if you check the current version of - https://ar-webstore.netlify.app/. They are in a single row placed side-by-side.
So, the buttons are disturbed on mobile because of your changes. I want you to fix that before merging this PR.

**Comment by 0xabdulkhalid** [comment]
@ShwetKhatri2001 Does i want to place the buttons in this position for mobiles ?

image

**Comment by ShwetKhatri2001** [comment]
> @ShwetKhatri2001 Does i want to place the buttons in this position for mobiles ?
> 
> image

Yes, this works. make sure after entering the AR view they are easy to view and clickable too.

**Comment by 0xabdulkhalid** [comment]
@ShwetKhatri2001 Now this PR is ready to be merged 🚀

**Comment by ShwetKhatri2001** [comment]
Yes, it's looking good. But your branch is 2 commits behind the master branch. Just update it, so that I can confirm everything works with the current version.

**Comment by 0xabdulkhalid** [comment]
Done @ShwetKhatri2001 👍🏻

**Comment by ShwetKhatri2001** [comment]
Good Work @0xabdulkhalid 👍 ! Merging now.

**Review by ShwetKhatri2001 — APPROVED** [review]

**Pull request merged**
