### PR TITLE
Added Responsive Feedpage Page

### PR DESCRIPTION
**Pull request by akanksha984**
#35 issue.

image
image

This is fully responsive page.
@ShwetKhatri2001 please look upon it

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Great work  @akanksha984 ! But this PR has got merge conflicts. Please solve those, probably you just need to use the latest `ModelViewer.js` file and then you can add `Feedback` Link instead of `Products` since we don't have any route for products but have one for feedback now.

**Comment by akanksha984** [comment]
@ShwetKhatri2001 please check now

**Comment by ShwetKhatri2001** [comment]
There is a syntax error because of which the build has failed. 
Check everything working fine by running the app locally before pushing it.

image

Fix that, Check the Netlify preview, and let me know.  
Also, as I mentioned above you need to add that `Feedback` link instead of the `Products` link in the `Header` component and remove it from `ModelViewer`.

**Comment by akanksha984** [comment]
Updating.. @ShwetKhatri2001

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 👍 Merging it. 
I'm not sure if it will be counted or GSSoC'23 or not, but appreciate for contribution. 
Keep Contributing 🚀

**Pull request merged**
