### PR TITLE
Updated the README.md

### PR DESCRIPTION
**Pull request by the-amazing-atharva**
Fixes issue #50

### CODE REVIEW

**Review by ShwetKhatri2001 — CHANGES_REQUESTED** [review]
@the-amazing-atharva The content you've changed is not much readable here, try to highlight it some other way, please ( if you want to ).

**Comment by ShwetKhatri2001** [comment]
@the-amazing-atharva  we have updated many things in the last two weeks.
Go through the current version and let me know if you want to make some changes to the current version via this PR else I can close this PR.

**Comment by the-amazing-atharva** [comment]
All the required changes are done imo!

**Comment by ShwetKhatri2001** [comment]
@the-amazing-atharva the kind of changes you've made will not help improve the documentation for this project I guess.
we have updated many things in the last three weeks.
Go through the current version and let me know if you want to make some changes to the current version via this PR else I can close this PR.

**Comment by ShwetKhatri2001** [comment]
Closing this because the PR has not been updated for a long time and the current changes are not required for the project.

**Pull request closed without merging**
