### PR TITLE
fix: model viewer component overflow 🛠

### LINKED ISSUE #125: [BUG]: incorrect measurements for component causing elements overflow 🪲
### Description

- The bug is about improper padding and margin values that have been applied for the model viewer component. Due to this the elements are pretend to overflowed at outer region.
- This needs to be resolved otherwise this causes bad impression on User Interface of AR-Webstore Website.

### Screenshots

image

### Any additional information?

_No response_

### What browser are you seeing the problem on?

Firefox

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by 0xabdulkhalid**
## Changes proposed
|||
|:---:|:---:|
|**BEFORE**| image |
|**AFTER**| Screenshot 2023-07-23 at 21-47-06 AR-Webstore |

PS: Don't take the both weird looking buttons on model viewer as issue, i already created a PR for that. After merge that will be fixed as well.

## Check List
- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by 0xabdulkhalid** [comment]
Hey there @ShwetKhatri2001 👋🏻 

Please make sure to review this PR.

Thank you!

**Comment by ShwetKhatri2001** [comment]
I also asked for setting the plus button. Did you check it ?

**Comment by 0xabdulkhalid** [comment]
The changes has been made as you requested @ShwetKhatri2001 🛠️ 

Now you can verify them.

**Comment by ShwetKhatri2001** [comment]
Well Done 🙌 This can be merged now.

**Review by ShwetKhatri2001 — APPROVED** [review]

**Pull request merged**
