### PR TITLE
fix: Added styles.yml and documentation.yml Files in GitHub ISSUE TEMPLATES

### LINKED ISSUE #133: [Feature] : Add documentation.yml and styles.yml Files for GitHub Issue Templates
### Description

**documentation.yml (Custom ISSUE_TEMPLATE):**
- The documentation.yml file serves as a custom ISSUE_TEMPLATE for your GitHub repository, specifically focused on documentation-related issues. When contributors or users of your project want to report documentation-related problems, improvements, or requests, they can create a new issue using this template.
- The contents of documentation.yml could include prompts or guidelines to help users structure their documentation-related issue reports effectively. For example, it might ask them to provide specific details about the section/page of documentation they found confusing, suggest possible improvements, or even ask for clarifications about the issue they are experiencing.

**styles.yml (Custom ISSUE_TEMPLATE):**
- The styles.yml file, on the other hand, serves as a custom ISSUE_TEMPLATE for issues related to coding style, code formatting, and linting rules within your GitHub repository. This template helps contributors or users report code style-related concerns or seek guidance on adhering to the project's coding standards.
- The contents of styles.yml might include specific questions or prompts related to coding style, requesting users to provide examples of code snippets that need formatting adjustments or explanation. Additionally, you might include instructions on how to check code against the project's style guidelines and best practices.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by NarendraKoya999**
## Changes proposed
- **Created styles.yml and documentation.yml Files in GitHub Issue Templates Folder.**
- **After that, I have added Suitable Code Placed in Respective Files.**

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by NarendraKoya999** [comment]
Hi @ShwetKhatri2001 . Please Review on this PR and Add Valid Level Labels to It under GSSOC'23 Contributor.

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊 Congrats on your first PR getting merged on AR-Webstore 🚀Keep Contributing 👍

**Comment by NarendraKoya999** [comment]
Hi @ShwetKhatri2001 . You can add Level 1 Label. Is it for My PR. Please add upper Level 2 Label. In all other Repository, that respective Admins added Level 2 Label look like Same Adding these Two Files. Kindly request You.

**Comment by ShwetKhatri2001** [comment]
Why the styles and documentation templates are not coming up after merging this PR when I try opening a new issue?
Fix it in your next PR. I'll upgrade the assigned level on this PR once it starts working.

**Comment by NarendraKoya999** [comment]
> Why the styles and documentation templates are not coming up after merging this PR when I try opening a new issue? Fix it in your next PR. I'll upgrade the assigned level on this PR once it starts working.

Sure @ShwetKhatri2001 . Some Indentation Problems is There. I can checked Just Now.

**Pull request merged**
