### PR TITLE
Set about us for all screen types

### PR DESCRIPTION
**Pull request by Nandini80**
## Fixes Issue
-I've adjusted the styling to ensure that the 'leaning explore' section is now responsive across various screen sizes.
-Improved the CSS part of 'about us' page.
image

image

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
The links are overflowing as I see in the deploy preview.

image

Also, here they are not taking full-width and looking small,

**Comment by Nandini80** [comment]
well it is not showing something like this
Even if I zoom it 300% it is showing something like this.

image

**Comment by Nandini80** [comment]
Kindly review it again

**Comment by ShwetKhatri2001** [comment]
No, it's the same. Actually, it's breaking at a few viewport points only if you see it on our live version, but your changes are getting applied on all the points and breaking the existing UI.

**Comment by ShwetKhatri2001** [comment]
Look at the latest code. The layout has been changed which is solving the issue to some extent. 
At some places it's breaking you can have a look at that.

**Pull request closed without merging**
