### PR TITLE
Contact Us form added with Formsubmit for receiving form data

### LINKED ISSUE #57: [Feature] Contact us section
### Description

I want to add a contact us section .

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by AnupK1234**
Created a responsive Contact Us form and integrated it with [Formsubmit](https://formsubmit.co/) which will send the form data to a user's email id.

## Closes #57 
[Feature] Contact us section

## Screenshot
Screenshot 2023-12-14 013710

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Good work, but there is a scope of improvement.

First, it's sending me an email to activate the form, but when I open it, it's saying 'Not a valid link' ( Confirmation token not found.). Test it at your end using your mail id.

Second, try to improve the UI and use current theme colours like white, black or gray. 
You may have input fields as present in the Feedback form and change the submit button as well.

**Comment by AnupK1234** [comment]
**Update:** UI of Contact form changed, form submission working perfect.
Screenshot 2023-12-17 235526

**Comment by ShwetKhatri2001** [comment]
Hey ! I'd like to merge this PR, but there was a `.env` file and I thought it was unnecessary. So I removed it, but it's causing an issue in the deployment. Are you using that file ?

**Review by ShwetKhatri2001 — APPROVED** [review]

**Comment by ShwetKhatri2001** [comment]
@AnupK1234 Will you be able to look at this within next few days ?

**Comment by AnupK1234** [comment]
> @AnupK1234 Will you be able to look at this within next few days ?

Ok Assign me this.

**Comment by ShwetKhatri2001** [comment]
Just fix it on this PR or raise a new one if you want to. You're already assigned the issue.

**Comment by ShwetKhatri2001** [comment]
@AnupK1234 , please try to fix it within the next 3 days.

**Comment by ShwetKhatri2001** [comment]
Closing this because of inactivity.

**Pull request closed without merging**
