### PR TITLE
responsive ness improved for below 1000px

### PR DESCRIPTION
**Pull request by Devesh-Daku**
solved the #169 issue 

## Fixes Issue

fixed the footer for 1000px and below ,

## Changes proposed

I improved the responsiveness of the website 
I didn't touched the original desktop view of website , the footer for desktop view 1000px above is same as it was already

## Check List (Check all the applicable boxes) 

- [yes ] My code follows the code style of this project.
- [not much  I guess] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

https://github.com/ShwetKhatri2001/AR-Webstore/assets/121988601/58a3aab1-bccb-4566-a006-1e5388d33b61

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Hey ! You have improved few parts which is good, but disturbed few as well.

For example, 
The email section and copyright text are not at the center here.
image

Too many links in a small place here,
image

**Comment by ShwetKhatri2001** [comment]
I think the only area which need some responsiveness is when we have three columns of links . We can have four columns of links there instead if we utilize the space properly. You may fix that only and keep the other things as they were.

image

**Comment by Devesh-Daku** [comment]
Actually your whole website needs to be responsive, 
Because adjusting footer with website is getting bit complicated, so finally i came up with this. 
In my opinion it is still better than the website now you have.

**Comment by ShwetKhatri2001** [comment]
As I described earlier it's a bit better on few screen widths, but making it bad in few others.
In the most used screen widths, the existing version is already better and I would not prefer to disturb it.

So, if the footer and all the elements present inside can be responsive for all breakpoints, then I'd be happy to merge this.

**Comment by ShwetKhatri2001** [comment]
Closing this PR because of inactivity.

**Pull request closed without merging**
