### PR TITLE
added navbar

### PR DESCRIPTION
**Pull request by tanujbordikar**
## Fixes Issue
Issue Solved #99 

## Changes proposed

In this PR, I have added a Responsive code for the navbar with Title (AR Webstore) and four menu list like Home, About, Products and Contact page.

**Changes:**
navbar-ar

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Good work @tanujbordikar , Do some small changes and you will be good to go.
- Add a logo along with the title ( AR-Webstore ) 
- Have you covered the responsiveness of Navbar for mobile, and how it will look on mobile ?
  I found some parts of the website are not responsive, but the Navbar should be responsive irrespective of other elements on 
  any page.

**Comment by tanujbordikar** [comment]
> Good work @tanujbordikar , Do some small changes and you will be good to go.
> 
> * Add a logo along with the title ( AR-Webstore )
> * Have you covered the responsiveness of Navbar for mobile, and how it will look on mobile ?
>   I found some parts of the website are not responsive, but the Navbar should be responsive irrespective of other elements on
>   any page.

Okay sure I will work on that!

**Comment by tanujbordikar** [comment]
hey @ShwetKhatri2001, can you check it because i have made changes in multiple files like error.js and model.js to make it responsive. It was quite tough for me but still managed to make it responsive.

**Comment by ShwetKhatri2001** [comment]
It's good to be merged now! Good work 👍

**Comment by tanujbordikar** [comment]
yeah i am raising a new one!

**Pull request closed without merging**
