### PR TITLE
#10 added

### LINKED ISSUE #10: Add depandabot
Dependabot is an automated dependency management tool that helps developers keep their projects up to date by automatically monitoring and updating dependencies when new versions are released. 
@ShwetKhatri2001 please assign this issue to me under GSSoC 23 label i will deliver quality work

### PR DESCRIPTION
**Pull request by k-deepak04**
@ShwetKhatri2001 depandabot added
please assign gssoc label to the PR 
i will search for more issues in the repo and try to contribute :)

Fixed #10

### CODE REVIEW

**Review by ShwetKhatri2001 — CHANGES_REQUESTED** [review]
@k-deepak04 Can you please make the interval `weekly` instead of `daily` since getting updates on a daily basis can hamper other tasks of the project.

**Comment by k-deepak04** [comment]
@ShwetKhatri2001 sure

**Review by ShwetKhatri2001 — CHANGES_REQUESTED** [review]
Correct `weekely` to `weekly` please. It may create errors after merge.

**Comment by k-deepak04** [comment]
@ShwetKhatri2001 done

**Comment by ShwetKhatri2001** [comment]
Now its Good 🎉Congrats on your first PR getting merged on AR-Webstore @k-deepak04  🚀

**Comment by k-deepak04** [comment]
Thanks :)

**Comment by k-deepak04** [comment]
@ShwetKhatri2001 bro please remove these labels as i have added the bots in other repo also
so it will be counted in spam 
Happy to contribute , will look for some other issues 
just remove the labels thanks :)

**Comment by k-deepak04** [comment]
@ShwetKhatri2001 please add the labels, as i have made changes and changed this to weekly i guess it will be counted in gssoc, sorry for the inconvenience caused.

**Pull request merged**
