### PR TITLE
Added : About page

### LINKED ISSUE #171: Add an "About Us" page
### Description

Currently About Us page is directly redirecting GitHub page. I want to add a separate About Us page with all the information given in the Git Hub.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Surajit0573**
fixed #171
## Fixes Issue
Currently About Us page is directly redirecting GitHub page.

## Changes proposed
 I added a separate About Us page with all the information given in the Git Hub.

image

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Good work ! 
Just found some small issues to be fixed. Fix those and it will be good to be merged.

- The content is different then what's present in the README.md file. Paragraphs are shorter.
Also, see if you can add some emojis / icons to differentiate the sections as shown in the README.md file.

- The image is overflowing from the page and adding a scroll at bottom.

Screenshot 2023-12-12 at 7 30 20 PM

**Comment by Surajit0573** [comment]
Okey

**Comment by Surajit0573** [comment]
@ShwetKhatri2001 Fixed.

image
image

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊  Congrats on your first PR getting merged on AR-Webstore @Surajit0573 🚀 Keep Contributing 👍

**Pull request merged**
