### PR TITLE
error page added

### LINKED ISSUE #34: Adding error 404 page
### Description

Hey,
I want to add an error 404 page to the website.
Thanks and Regards,
Vibhuti Chandrakar.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [x] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by mandliyarajendra11**
## Fixes Issue

close  #34 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by ShwetKhatri2001 — CHANGES_REQUESTED** [review]
It's giving error that the import route for ErrorPage doesn't exist, since you have changed the path of `ErrorPage.js`. 

image

- Create a new folder always for a new page / reusable component.
For example here, create a folder `ErrorPage` and have your files with the names `ErrorPage.js` and `ErrorPage.css`. 

- Once you raise a new PR, make sure your changes are working on the Netlify deploy-preview and if it fails, then check the deploy log and try resolving the issues present there.

**Comment by mandliyarajendra11** [comment]
> It's giving error that the import route for ErrorPage doesn't exist, since you have changed the path of `ErrorPage.js`.
> 
> image
> 
> * Create a new folder always for a new page / reusable component.
>   For example here, create a folder `ErrorPage` and have your files with the names `ErrorPage.js` and `ErrorPage.css`.
> * Once you raise a new PR, make sure your changes are working on the Netlify deploy-preview and if it fails, then check the deploy log and try resolving the issues present there.

oh i forget to commit app.js file

**Comment by mandliyarajendra11** [comment]
check now

**Comment by ShwetKhatri2001** [comment]
> * Create a new folder always for a new page / reusable component.
>   For example here, create a folder `ErrorPage` and have your files with the names `ErrorPage.js` and `ErrorPage.css`.

This remains.

**Comment by mandliyarajendra11** [comment]
> 

check again

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 👍

**Pull request merged**
