### PR TITLE
Feed back page

### LINKED ISSUE #177: [style]: FeedBack Page
### What's the style idea?

I want to Improve the Feedback Page and make it more visually appealing and responsive.

### Add screenshots

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CODE_OF_CONDUCT.md)
- [ ] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Yuvraj960**
Added the code for the new feedback page with SMTPJs Functionality

## Fixes Issue

Closes #177 

## Changes proposed

Modified the code of FeedBack Page

## Check List

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by ShwetKhatri2001 — COMMENTED** [review]
Great @Yuvraj960 ! Just got a few things to be improved, it can be merged after that.

- Add two more fields in the form `Name` and `Email`, so that we can find who has sent the feedback.
- Replace `Leave a Message` with `Your Feedback ✍️ Our Evolution 🚀`
- Replace`Your Data Successfull Received` with `Thanks ! We've received your feedback`.
- Clear the form after submission.
- Remove the Old Code.

**Comment by Yuvraj960** [comment]
Hello @ShwetKhatri2001, I am done with the changes you want in my Code. I have also committed them on the branch. But as I am new to GitHub, I am not able to see that my changes are applied on my existing pull request or not. Can you please check my code again. If the changes are not visible, please let me know how do I update the code in this PR.

**Comment by ShwetKhatri2001** [comment]
After submitting the form everytime I'm getting `Something went wrong` now. Check that.
Also, send some references about the Elastic Email account setup you need to send emails.

The changes you commit to the branch of this PR will reflect in `Files Changed` section of the PR and can be previewed in the Netlify's Deploy Preview
( https://deploy-preview-229--ar-webstore.netlify.app ). Check these two things to make sure everything is working as expected.

**Comment by Yuvraj960** [comment]
@ShwetKhatri2001, You are having error because I haven't edited the mail address in the code as I said earlier. For that the solution is to edit the "To:" field (line 50 in the code) and fill up the mail address on which you want to receive the info (for the testing purposes). 
image

And for the elastic mail account, you can watch up one video: 
https://www.youtube.com/watch?v=z-_kZRe_P7c&t=96s&ab_channel=EducationAnalysist
From Time stamp 10:26 to 15:00, You will be clear how to setup a Elastic email account.

**Comment by ShwetKhatri2001** [comment]
I have created SMTP credentials with this email `shwetkhatri2001@gmail.com` , but it doesn't seem to be working.
I want `from` and `to` both to be that email address.

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊 Congrats @Yuvraj960 on your first PR getting merged on AR-Webstore 🚀 Keep Contributing 👍

**Pull request merged**
