### PR TITLE
added docker functionality

### LINKED ISSUE #218: Addition of Docker
### Description

I visited the website and GitHub repo, and while skimming through project I wondered that is there any way to get it locally instantly without node modules but there are none, Implementing DockerFile could be a great thing

### Screenshots

image

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### PR DESCRIPTION
**Pull request by Girishbari**
Fixes #218 

Added dockerfile, there will some change required in readme file such project can be run `docker run -p 3000:3000` ar-webstore
- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
So, is it just a single command or some more things required in the docker-based setup since we need to update the documentation accordingly. Also, better if you can only do it.

**Comment by Girishbari** [comment]
currently it is just one command but I did suggest one more thing that you can do
1. make an account on docker hub (similar to GitHub but only for images)
2.  we'll upload this project there, in that sense one even don't require to clone the project, one can use
     `docker pull` to get the project from there
3. this will help us to deploy project vercel or on railway

**Comment by Girishbari** [comment]
ping me when you're ready

**Comment by ShwetKhatri2001** [comment]
I will surely see this and get back to you in a few days. 
You may start with other fixes/enhancements in the meantime if you like to.

**Comment by ShwetKhatri2001** [comment]
The project's image is deployed on the docker hub. 
It will work for the Dockerfile you've added. Include a `.dockerignore` file having file/folder names that are not required.

Test it and write good documentation for this setup.
Mention these commands with some description in README.md,
`docker -v` to check docker installed locally successfully
`docker pull shwetkhatri2001/ar-webstore`
`docker images` to check an image exists with the name 'shwetkhatri2001/ar-webstore'
`docker run -p 3000:3000 shwetkhatri2001/ar-webstore`

**Comment by Girishbari** [comment]
sure

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊 Congrats @Girishbari on your first PR getting merged on AR-Webstore  🚀 Keep Contributing 👍

**Pull request merged**
