### PR TITLE
fix: Added sign-in and sign-up

### PR DESCRIPTION
**Pull request by IrfanshaikH-7**
**Fixes** #100 

**Changes:** Added Sign-in and Sign-up pages

Screenshots:
Screenshot 2024-01-23 185151
Screenshot 2024-01-23 185208

Please let me know if any changes are required

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Add a link on the Navbar as `Sign In` so that I can check it in the deploy preview. 
In the image of the `/sign-in` page, I see the title `Sign up`, change it to `Sign In`.

Also, the yellow background color of the buttons isn't matching with our existing theme colors. 
Change it to something else like black or gray.

**Comment by IrfanshaikH-7** [comment]
Changes added -

**Comment by ShwetKhatri2001** [comment]
Routes are added in two files. Keep them in `App.js`. Currently, other pages are not accessible because of missing routes in `index.js`, make them accessible. Also, Keep the Navbar on top of sign-in and sign-up pages as well.

**Comment by IrfanshaikH-7** [comment]
> Routes are added in two files. Keep them in `App.js`. Currently, other pages are not accessible because of missing routes in `index.js`, make them accessible. Also, Keep the Navbar on top of sign-in and sign-up pages as well. It can be merged after that.

if you say so

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊 Congrats @IrfanshaikH-7  on your first PR getting merged on AR-Webstore 🚀 Keep Contributing 👍

**Pull request merged**
