### PR TITLE
Feature : Incorporated correct structure, enabled styling and content display

### LINKED ISSUE #137: [Feature]: Addition  of proper HTML structure in the error.css file
### Description

One major issue with the original code is the lack of proper HTML structure. Without a complete HTML structure, the code would not render correctly in a web browser, and any CSS styling would not have any effect.

To solve this issue, we will provide a modified version of the code with a proper HTML structure. We will wrap the CSS classes within a basic HTML page.

### Screenshots

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by tamannaaaaa**
Closes #137 

## Fixes Issue

The original code lacks proper HTML structure, hindering rendering; the modified version incorporates correct structure, enabling effective styling and content display.

## Changes proposed

Missing HTML structure: The code provided is CSS only, and it lacks the necessary HTML structure. To create a complete error page, you should wrap the CSS classes within an HTML file. You can use the <html>, <head>, and <body> tags to structure the content properly.

Unclear button class: The class name .btn1 doesn't convey its purpose clearly. Consider renaming it to something more descriptive, like .error-btn or .error-button.

Inconsistent class naming: The class .text and .error-text seem to have similar purposes, as they both are used for text alignment and styling. It might be better to use a more consistent naming convention to make the code easier to understand and maintain.

Font-family usage: The font-family "Cursive" is being applied to the .error-text class, which might not be the best choice for an error message. Instead, you could use a more common font-family like "Arial," "Helvetica," or any other sans-serif font.

Missing link functionality: The .error class appears to be styled like a button, but it lacks any link or JavaScript functionality. To make it functional, you need to add an anchor tag <a> with an appropriate href attribute or JavaScript event handler.

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Actually, we don't need different HTML files for different pages when we use ReactJS. 
We need to add the required JS code and HTML to be rendered for a page / part of the page in a `[componentname]`.js file.

For example, `Error.js` file has a return statement that returns the HTML for the Error page.
Check the HTML elements there having `className` attribute ( that we use instead of `class` word ) and those classes are defined in `Error.css`.

You can try updating HTML tags and CSS code in those two files and take this opportunity to work on ReactJS.

**Comment by ShwetKhatri2001** [comment]
Actually, we don't need different HTML files for different pages when we use ReactJS. 
We need to add the required JS code and HTML to be rendered for a page / part of the page in a `[componentname]`.js file.

For example, `Error.js` file has a return statement that returns the HTML for the Error page.
Check the HTML elements there having `className` attribute ( that we use instead of `class` word ) and those classes are defined in `Error.css`.

You can try updating HTML tags and CSS code in those two files and take this opportunity to work on ReactJS.

**Comment by tamannaaaaa** [comment]
Okay got it ! I have done some changes in the index.css file in which the comments have been labeled for better clarity, and the properties for the body element have been reordered for consistency. The code maintains its original purpose and structure while being a bit cleaner and more organized. I will create a new PR. Please check it out.

**Comment by ShwetKhatri2001** [comment]
Closing this PR since the proposed changes are added via another PR.

**Pull request closed without merging**
