### PR TITLE
Full screen added

### LINKED ISSUE #96: [Feature] Full screen mode for 3D Viewer
### Description

Add a button near/on the 3D viewer card present currently which should show the 3D viewer on the entire screen with all controls working there to give the user a broader view of the product in 3D. Also, using the same button the user should be able to get out of that full-screen mode.

### Screenshots

Go through this [Sketchfab example](https://sketchfab.com/3d-models/oversized-drop-shoulder-sweatshirt-c533289593ed4a7094bc2e0cefebde12), we can have a similar full-screen button present at the right-bottom functioning similarly.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by mandliyarajendra11**
## Fixes Issue 

closed #96 

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
It's done really well! Let's fix some minor UI issues to make it excellent.

- The full-screen mode isn't supporting the help feature. Increase the text area and font size proportional to the viewer's width.

Screenshot (6)

- The buttons are very close to the corner, especially in the full-screen mode if you see it on mobile the buttons are hard to click. So keep some margin from the borders ( see how the "View in your space button is placed ) and make the buttons large in size to make them easily clickable. Also, set cursor=pointer for buttons.

**Comment by mandliyarajendra11** [comment]
> It's done really well! Let's fix some minor UI issues to make it excellent.
> 
> * The full-screen mode isn't supporting the help feature. Increase the text area and font size proportional to the viewer's width.
> 
> Screenshot (6)
> 
> * The buttons are very close to the corner, especially in the full-screen mode if you see it on mobile the buttons are hard to click. So keep some margin from the borders ( see how the "View in your space button is placed ) and make the buttons large in size to make them easily clickable. Also, set cursor=pointer for buttons.
> 
> 

okay

**Comment by mandliyarajendra11** [comment]
@ShwetKhatri2001 check please

**Comment by mandliyarajendra11** [comment]
but i cant find any problem working ..... 
IMG_20230707_152433

**Comment by ShwetKhatri2001** [comment]
> but i cant find any problem working ..... 
> IMG_20230707_152433
> 

Which URL you're trying. Is it deploy-preview-107--ar-webstore.netlify.app ? Can you please shar a screen recording if possible !

**Comment by mandliyarajendra11** [comment]
> > but i cant find any problem working .....
> > IMG_20230707_152433
> 
> Which URL you're trying. Is it deploy-preview-107--ar-webstore.netlify.app ? Can you please shar a screen recording if possible !

yes you can see full screen button in the image

**Comment by ShwetKhatri2001** [comment]
Okay, I got the chair too. I guess they are now forcing us to use AR-Core only if it's installed on mobile. Although that's not a problem for us. 

Merging this for now. Thanks for your contribution 👍.

**Review by ShwetKhatri2001 — APPROVED** [review]

**Comment by ShwetKhatri2001** [comment]
> I guess they are now forcing us to use AR-Core only if it's installed on mobile. Although that's not a problem for us.
> 
This is the case on the local server and deploy-previews only. 
On final production it's opening AR as expected. So, no worries.

**Pull request merged**
