### PR TITLE
Added animation in About page.

### LINKED ISSUE #205: [Feature] Adding animation in about page.
### Description

I want to add animation in the picture in about page.
Please assign this issue to me under SWOC'24.

### Screenshots

Screenshot (189)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [X] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by yashi-15**
### Closes #205 

Animation added!

Kindly merge the PR or let me know for any further changes required to be made.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Can you add some basic animations such as floating from left or right to a few more elements? 
It will make it valid for the `Easy` level then.

**Comment by yashi-15** [comment]
> Can you add some basic animations such as floating from left or right to a few more elements? It will make it valid for the `Easy` level then.

Sure! I'll do that! Also, I would like to change the orientation of elements in the following sections:

1.
Screenshot (190)

2.
Screenshot (191)

3.
Screenshot (192)

- I would like to change the font sizing and elements placement in these sections. This way it would be easier for me to integrate appropriate animating effects into them. 
- It'll make this page look better at the end for sure.

Allow me to do the above changes or let me know for any of your suggestion.

**Comment by ShwetKhatri2001** [comment]
Sure, you can make some minor changes to them required for adding animations. 
If you are changing the page completely then discuss the kind of changes you want to make in detail here.

**Comment by yashi-15** [comment]
Done! Kindly review the changes @ShwetKhatri2001 . Thankyou!

**Comment by ShwetKhatri2001** [comment]
Good work @yashi-15 . There are a few issues that I think you can fix quickly.

- Use a small font-size for mobile screen width since it's making it 

- Make this Section responsive for mobile



- Remove this scroll coming at the bottom because of the overflowing contributors' list I think.



- This cross icon isn't looking as expected in this PR's preview.

**Comment by yashi-15** [comment]
> Good work @yashi-15 . There are a few issues that I think you can fix quickly. You will get `Medium` level on this PR for fixing those.
> 
> * Use a small font-size for mobile screen width since it's making it scroll too much.
> * Make this Section responsive for mobile
> 
> 
> * Remove this scroll coming at the bottom because of the overflowing contributors' list I think.
> 
> 
> * This cross icon isn't looking as expected in this PR's preview.
> 
> 

I've made these changes. Please check and let me know... @ShwetKhatri2001

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊 Congrats @yashi-15 on your first PR getting merged on AR-Webstore 🚀 Keep Contributing 👍

**Pull request merged**
