### PR TITLE
Fix: about link

### LINKED ISSUE #206: [BUG] About in footer
### Description

It leads to github page instead of routing /about

### Screenshots

https://github.com/ShwetKhatri2001/AR-Webstore/assets/114663382/f7ec4617-6b9f-4988-b1af-411cc816b03d

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/ShwetKhatri2001/AR-Webstore/blob/master/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

### PR DESCRIPTION
**Pull request by AaadityaG**
## Changes proposed

Updating footer about link

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by AaadityaG** [comment]
Please consider this with SWOC tag! thank you!

**Comment by ShwetKhatri2001** [comment]
Check the preview. It opens the URL in a new tab. Fix that.

**Review by AaadityaG — COMMENTED** [review]
Its done... Please consider with SWOC tag

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊 Congrats @AaadityaG on your first PR getting merged on AR-Webstore 🚀 Keep Contributing 👍

**Comment by AaadityaG** [comment]
Thanks!

**Pull request merged**
