### PR TITLE
feat: added annotations using MODEL-VIEWER

### LINKED ISSUE #111: [Feature] Show features of the product in 3D viewer via Annotations
### Description

To show all important features of the product we can use [Annotations ( Camera Views ) by model-viewer](https://modelviewer.dev/examples/annotations/index.html#cameraViews). 

There will be an `i` button in the bottom-right corner with other buttons on click to which all the annotations ( features ) for that object ( product ) will be shown and they will be hidden once the button is clicked again ( like a toggle ). 
By default on load of the object, they will be hidden. Keep the annotations short and to the point ( not taking too much space ).

Also, keep in mind that different objects will have different positions and text for annotations. 
So, change the component in such a way that it can take all the dynamic annotations-data coming from outside and apply annotations for any object based on that data value.

### Screenshots

You should use [model-viewer-editor](https://modelviewer.dev/editor/) and try adding some hotspots there. 
You will get the code snippet on top of that page. For example, I created some here,

image

On clicking on the annotations the camera should target that position as shown in this [cameraViews example](https://modelviewer.dev/examples/annotations/index.html#cameraViews). After getting the code from the editor above you need to change it and add event listeners as shown in this example.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by Girishbari**
Fixes #111 

Added annotation part on each product using model-view
## Changes proposed

[x] - Correct; marked as done

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Great work @Girishbari !

Just want to confirm if you can achieve this small feature as described in the issue description.

> On clicking on the annotations the camera should target that position as shown in this [cameraViews example](https://modelviewer.dev/examples/annotations/index.html#cameraViews). After getting the code from the editor above you need to change it and add event listeners as shown in this example.

**Comment by Girishbari** [comment]
okay, will do

**Comment by Girishbari** [comment]
I think this would do 

https://github.com/ShwetKhatri2001/AR-Webstore/assets/38005544/33daa8df-aa03-4419-91f4-c716c693cc81

**Comment by ShwetKhatri2001** [comment]
Yes, it's good that you're moving to that annotation. but can you zoon in to that specific annotation ?

**Comment by ShwetKhatri2001** [comment]
Will you push some new changes ?

**Comment by Girishbari** [comment]
No I guess

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM 🎊 Congrats @Girishbari on your first PR getting merged on AR-Webstore 🚀 Keep Contributing 👍

**Pull request merged**
