### PR TITLE
Fixed responsiveness of website

### LINKED ISSUE #121: [BUG] Not responsive
### Description

image

I would like to make it responsive. It is not all responsive in mobile view

### Screenshots

_No response_

### Any additional information?

_No response_

### What browser are you seeing the problem on?

_No response_

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/rupali-codes/LinksHub/blob/main/CONTRIBUTING.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by akanksha984**
## Fixes Issue

Closes #121 

## Changes proposed
image

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] All new and existing tests passed.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
It's working well on a desktop, but if I open it on mobile then it's giving me a blank white screen.
The rendering is different for desktop and mobile ( in if-else ).

Try the deploy preview on mobile. 
If possible don't apply the changes directly on `model-viewer` and apply on the outer container.

**Comment by akanksha984** [comment]
@ShwetKhatri2001 #121 and #64 both are combined in this pr.. Please check it

**Comment by ShwetKhatri2001** [comment]
Everything looks working for #121 , but you need to create separate PRs for different issues 
( specially if you're a GSSoC'23 contributor )

So, you may just copy and paste the two files you've changed into a new branch ( created from `master` ) and raise a PR from that branch for #64 when you're done with it.

Only keep the changes you require for the responsiveness issue here. Remove the changes not required.

**Comment by akanksha984** [comment]
> Everything looks working for #121 , but you need to create separate PRs for different issues ( specially if you're a GSSoC'23 contributor )
> 
> So, you may just copy and paste the two files you've changed into a new branch ( created from `master` ) and raise a PR from that branch for #64 when you're done with it.
> 
> Only keep the changes you require for the responsiveness issue here and remove other changes.

Is there a way to undo my changes ?

**Pull request closed without merging**
