### PR TITLE
feat: variant selection

### LINKED ISSUE #113: [Feature] Color Variants for the Product in 3D
### Description

We all have seen how e-commerce platforms provide different variants of the same product to fulfill the color requirements of the user, where for the same design / material you get different color combinations. Why not provide this in 3D !

So, the idea is to provide an option ( dropdown for now ) to change product variants.
For reference, you should take a look at [model-viewer shoes-variants example](https://modelviewer.dev/examples/scenegraph/#variants) and try out the shoe variants there. 
Similar to this, the chair present currently on our platform also has two variants and we can create new variants on https://modelviewer.dev/editor/ as well, just as I created one here by changing different material's colors,

image

If you are creating new variants then you need to `Download Scene` from the editor to get updated `.glb` file. 
After that, you can use the code implementation they have provided in the example, where you will first get the list of available variants and then will update `variantName` based on the selected variant in the dropdown / UI.

### Screenshots

This is how the UI should look actually having the image-tabs for each variant,
image

But since we don't have a product-details page you may just add a dropdown for now to change variants between the viewer area and QR code ( on the right corner below the gray viewer area). 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines]
- [ ] I am willing to work on this issue (optional)
- [ ] I am a GSSoC'23 contributor

### PR DESCRIPTION
**Pull request by IrfanshaikH-7**
## Fixes Issue
Related issue: #113 
Closes #113 

## Changes proposed
added a feature where users can change variants of products if available - without interfering with other products in map.

## note
I haven't worked on UI. if we could conclude this features functionally I 'll do that then.

## Check List (Check all the applicable boxes) 

- [X] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Amazing work @IrfanshaikH-7 ! I hope it will work on all models having variants dynamically. but to test that, it will be better if you can have two more variants in the other 3 models as I described in https://github.com/ShwetKhatri2001/AR-Webstore/issues/113#issuecomment-1953015074.

A few more things you can update are some UI issues.
- Remove the extra similar chair as the product.
- Make sure all product details/images are inside the card during hover as well. 
You should put the dropdown inside the model-viewer section on the left of the `i` button ( without `Variant: `label) so that it can be switched in the full-screen mode as well.

image

Just fix these and I will merge the PR for `Hard`.

**Comment by ShwetKhatri2001** [comment]
Looks better now. Can you see this one last remaining thing? It will make the PR valid for `Hard` level.

> It will be better if you can have two more variants in the other 3 models as I described in https://github.com/ShwetKhatri2001/AR-Webstore/issues/113#issuecomment-1953015074.

**Comment by IrfanshaikH-7** [comment]
> Looks better now. Can you see this one last remaining thing? It will make the PR valid for `Hard` level.
> 
> > It will be better if you can have two more variants in the other 3 models as I described in [#113 (comment)](https://github.com/ShwetKhatri2001/AR-Webstore/issues/113#issuecomment-1953015074).

its giving me .glb file. how do I get the .usdz

**Comment by IrfanshaikH-7** [comment]
> Looks better now. Can you see this one last remaining thing? It will make the PR valid for `Hard` level.
> 
> > It will be better if you can have two more variants in the other 3 models as I described in [#113 (comment)](https://github.com/ShwetKhatri2001/AR-Webstore/issues/113#issuecomment-1953015074).

please review my PR now i have added two new models with vaients

**Review by ShwetKhatri2001 — APPROVED** [review]
LGTM

**Pull request merged**
