### PR TITLE
npm cmd update  

### PR DESCRIPTION
**Pull request by shivam-sharma7**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by ShwetKhatri2001 — CHANGES_REQUESTED** [review]
The changes made are different from the required changes. 
Check all the comments made on the issue.

**Comment by shivam-sharma7** [comment]
> The changes made are different from the required changes. Check all the comments made on the issue.

what do you mean by this? I the `README.md` need to be change because cmd is there to set up project and run locally.

**Comment by shivam-sharma7** [comment]
> Check [#47 (comment)](https://github.com/ShwetKhatri2001/AR-Webstore/issues/47#issuecomment-1567964047). I recommended to change it to `npm run start:live` to maintain the standard WebXR flow. For your Ref : [Develop your first WebAR app using WebXR and Three.js ](https://codemaker2016.medium.com/develop-your-first-webar-app-using-webxr-and-three-js-7a437cb00a92)

No problem :)

**Comment by ShwetKhatri2001** [comment]
Well done! It can be merged now!

**Pull request merged**
