### PR TITLE
Code Refactoring

### PR DESCRIPTION
**Pull request by simrraann8**
## Changes proposed

Import Order and Formatting:- Reordered imports for better organization and consistent formatting throughout the file.
Destructured Imports :-  Destructured imports from React Router for improved readability.
Simplified JSX Usage :- Removed unnecessary element prop wrappers for the ModelViewer and ErrorPage components.
Indentation and Spacing :- Ensured consistent indentation and spacing for improved code presentation.

## Check List (Check all the applicable boxes) 

- [ x] My code follows the code style of this project.
- [x ] My change requires changes to the documentation.
- [ x] I have updated the documentation accordingly.
- [ x] All new and existing tests passed.

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
@simrraann8 There are merge conflicts in 'App.js` file. 
Pull the latest master branch to your branch and solve the conflicts and don't remove any code added previously while fixing them

**Comment by simrraann8** [comment]
Hey, @ShwetKhatri2001 Do I have to make another PR then?

**Comment by ShwetKhatri2001** [comment]
You can update this PR as well.
Follow these steps :

- First, go to your forked repo on GitHub and update all your branches using `Sync fork`  and `Update branch`.
image

- Second, Open VS Code / Any Code Editor and update all your branches there using `git pull`.

- On the branch you're using in this PR, just replace the `App.js` file having your changes , add the changes and commit.

**Comment by simrraann8** [comment]
@ShwetKhatri2001 It's not happening , I have tried several times. You can close this PR. Thanks for assigning.

**Pull request closed without merging**
