### PR TITLE
updated readme

### LINKED ISSUE #9: add tech stack badges/shields
i would like to add the tech stack shields in the readme file.
this will give a quick view of all the techstacks used in the project
@ShwetKhatri2001  pls assign me this issue . i am a gssoc contributor
example of the tech stack:
image

### PR DESCRIPTION
**Pull request by mridulsaggi**
added tech stack badges(shields)

Fixes #9

### CODE REVIEW

**Comment by ShwetKhatri2001** [comment]
Resolve the merge conflicts and also a suggestion to use colors of the badges same as the color being used in that technology's logo.

**Comment by ShwetKhatri2001** [comment]
The merge conflicts are still there. Kindly pull the latest master branch and add changes you want without disturbing any existing functional code.

**Comment by mridulsaggi** [comment]
@ShwetKhatri2001 i have made the required changes and removed the conflicts. please merge

**Comment by ShwetKhatri2001** [comment]
LGTM 🎉Congrats on your first PR getting merged on AR-Webstore @mridulsaggi  🚀

**Pull request merged**
